n = float(input('Digite um número em m[metros]: '))
print('[{}]m = [{:.3f}] Kilômetros'.format(n,n/1000))
print('[{}]m = [{:.3f}] Hectômetros'.format(n,n/100))
print('[{}]m = [{:.1f}] decâmetros'.format(n,n/10))
print('[{}]m = [{}] decímetros'.format(n,n*10))
print('[{}]m = [{}] centrímetros'.format(n,n*100))
print('[{}]m = [{}] milímetros'.format(n,n*1000))