n = input('Digite algo: ')
print('É Numerico? [{}]'.format(n.isnumeric()))
print('É Alfabético? [{}]'.format(n.isalpha()))
print('É um espaço? [{}]'.format(n.isspace()))
print('É um dígito? [{}]'.format(n.isdigit()))
print('É MAIÚSCULO? [{}]'.format(n.isupper()))
print('É minusculo? [{}]'.format(n.islower()))
print('É Alfanúmérico? [{}]'.format(n.isalnum()))
print('É decimal? [{}]'.format(n.isdecimal()))
print('É Captalized? [{}]'.format(n.istitle()))